### ISSUE TITLE
potential error in training models

### ISSUE THREAD

**Issue by pitrieger** [aristotle-tek/Classif_Accuracy_Polarization#1]
Hi, I think there is an error with line 112 in the utils.py script. Doesn't this override the other three classifiers with LogisticRegression? As far as I can tell, this line should be in the previous for-loop.

**Comment by aristotle-tek** [comment]
Hi, thanks for this catch - I have updated the code to remove this (debugging line, introduced in later checks, which does not alter the findings in our published article).
